import os
import requests
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from datetime import datetime


def generate_incident_report(incident, upload_folder):

    report_folder = "reports"
    os.makedirs(report_folder, exist_ok=True)

    filename = f"incident_report_{incident.id}.pdf"
    filepath = os.path.join(report_folder, filename)

    c = canvas.Canvas(filepath, pagesize=A4)

    width, height = A4
    y = height - 50

    def ensure_space(required_space):
        nonlocal y
        if y < required_space:
            c.showPage()
            y = height - 50


    # -------------------------
    # HEADER
    # -------------------------

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, "OFFICIAL INCIDENT REPORT")

    y -= 30

    c.setFont("Helvetica", 10)
    c.drawString(50, y, "Generated by Municipal Incident Reporting System")

    y -= 30


    # -------------------------
    # INCIDENT SUMMARY
    # -------------------------

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Incident Summary")

    y -= 20

    c.setFont("Helvetica", 11)

    time_value = ""
    if incident.created_at:
        time_value = incident.created_at.strftime("%Y-%m-%d %H:%M:%S")

    c.drawString(50, y, f"Incident ID: {incident.id}")
    y -= 18

    c.drawString(50, y, f"Type: {incident.type}")
    y -= 18

    c.drawString(50, y, f"Date Reported: {time_value}")
    y -= 18

    c.drawString(50, y, f"Status: {incident.status}")
    y -= 25


    # -------------------------
    # LOCATION
    # -------------------------

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Location")

    y -= 20

    c.setFont("Helvetica", 11)

    address = incident.address or "Not Available"

    c.drawString(50, y, f"Address: {address}")
    y -= 18

    c.drawString(
        50,
        y,
        f"Coordinates: {incident.latitude}, {incident.longitude}"
    )

    y -= 25


    # -------------------------
    # DESCRIPTION
    # -------------------------

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Description")

    y -= 20

    c.setFont("Helvetica", 11)

    description = incident.description or "No description provided."

    text = c.beginText(50, y)
    text.setLeading(15)

    for line in split_text(description, 90):
        text.textLine(line)

    c.drawText(text)

    y = text.getY() - 25


    # -------------------------
    # DETAILED REPORT
    # -------------------------

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Detailed Report")

    y -= 20

    narrative = f"""
On {time_value}, an incident categorized as "{incident.type}" was officially reported through the Municipal Incident Reporting System. The report was captured and recorded in real-time, ensuring prompt visibility for monitoring and potential response by the concerned authorities.

The incident was reported at the location identified as {address}. Based on geospatial data, the exact coordinates of the incident are {incident.latitude}, {incident.longitude}. This precise location information supports accurate mapping, situational awareness, and response planning.

According to the reporting individual, the incident is described as follows:

"{description}"

To support the validity of the report, photographic evidence was submitted through the system. Additionally, a map representation of the pinned location has been generated and included in this document to assist authorities in visualizing the exact area of the incident.

This report is generated as part of the municipality's initiative to strengthen incident documentation, improve transparency, and enhance overall emergency response efficiency.
"""

    text = c.beginText(50, y)
    text.setLeading(15)

    for line in split_text(narrative.strip(), 90):
        text.textLine(line)

    c.drawText(text)

    y = text.getY() - 25


    # -------------------------
    # IMAGE SECTION
    # -------------------------

    has_photo = False
    photo_path = ""

    if incident.photo:
        photo_path = os.path.join(upload_folder, incident.photo)
        if os.path.exists(photo_path):
            has_photo = True


    # -------------------------
    # MAP (FINAL RELIABLE FIX)
    # -------------------------

    has_map = False
    map_path = os.path.join(report_folder, f"map_{incident.id}.png")

    if incident.latitude and incident.longitude:

        lat = incident.latitude
        lon = incident.longitude

        # ---- TRY GOOGLE ----
        GOOGLE_MAPS_API_KEY = "YOUR_API_KEY_HERE"

        try:
            google_url = (
                f"https://maps.googleapis.com/maps/api/staticmap"
                f"?center={lat},{lon}"
                f"&zoom=17"
                f"&size=600x300"
                f"&markers=color:red%7C{lat},{lon}"
                f"&key={GOOGLE_MAPS_API_KEY}"
            )

            response = requests.get(google_url, timeout=10)

            if response.status_code == 200 and len(response.content) > 5000:
                with open(map_path, "wb") as f:
                    f.write(response.content)
                has_map = True

        except Exception as e:
            print("Google map failed:", e)

        # ---- FALLBACK (OSM) ----
        if not has_map:
            try:
                osm_url = (
                    f"https://staticmap.openstreetmap.de/staticmap.php"
                    f"?center={lat},{lon}"
                    f"&zoom=15"
                    f"&size=600x300"
                    f"&markers={lat},{lon},red"
                )

                response = requests.get(osm_url, timeout=10)

                if response.status_code == 200:
                    with open(map_path, "wb") as f:
                        f.write(response.content)
                    has_map = True

            except Exception as e:
                print("OSM fallback failed:", e)


    # -------------------------
    # DRAW IMAGES
    # -------------------------

    if has_photo or has_map:
        ensure_space(220)

    img_width = 3 * inch
    img_height = 2 * inch

    x_photo = 50
    x_map = 320

    if has_photo or has_map:

        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y, "Photo Evidence & Location Map")

        y -= 15

        if has_photo:
            try:
                c.drawImage(
                    photo_path,
                    x_photo,
                    y - img_height,
                    width=img_width,
                    height=img_height,
                    preserveAspectRatio=True
                )
            except:
                print("Photo render failed")

        if has_map and os.path.exists(map_path):
            try:
                c.drawImage(
                    map_path,
                    x_map,
                    y - img_height,
                    width=img_width,
                    height=img_height
                )
            except Exception as e:
                print("Map render failed:", e)

        y -= (img_height + 20)


    # -------------------------
    # FOOTER
    # -------------------------

    local_time = datetime.now()

    c.setFont("Helvetica", 9)
    c.drawString(
        50,
        40,
        f"Report generated on {local_time.strftime('%Y-%m-%d %H:%M:%S')}"
    )

    c.save()

    return filepath


def split_text(text, length):

    words = text.split()
    lines = []
    current = ""

    for word in words:

        if len(current + " " + word) <= length:
            current += " " + word
        else:
            lines.append(current.strip())
            current = word

    if current:
        lines.append(current.strip())

    return lines