import os
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from datetime import datetime


def generate_incident_report(incident, upload_folder):

    # Create reports folder if not exists
    report_folder = "reports"
    os.makedirs(report_folder, exist_ok=True)

    filename = f"incident_report_{incident.id}.pdf"
    filepath = os.path.join(report_folder, filename)

    c = canvas.Canvas(filepath, pagesize=A4)

    width, height = A4
    y = height - 50


    # -------------------------
    # HEADER
    # -------------------------

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, "OFFICIAL INCIDENT REPORT")

    y -= 30

    c.setFont("Helvetica", 10)
    c.drawString(50, y, "Generated by Municipal Incident Reporting System")

    y -= 30


    # -------------------------
    # INCIDENT SUMMARY
    # -------------------------

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Incident Summary")

    y -= 20

    c.setFont("Helvetica", 11)

    time_value = ""
    if incident.created_at:
        time_value = incident.created_at.strftime("%Y-%m-%d %H:%M:%S")

    c.drawString(50, y, f"Incident ID: {incident.id}")
    y -= 18

    c.drawString(50, y, f"Type: {incident.type}")
    y -= 18

    c.drawString(50, y, f"Date Reported: {time_value}")
    y -= 18

    c.drawString(50, y, f"Status: {incident.status}")
    y -= 25


    # -------------------------
    # LOCATION
    # -------------------------

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Location")

    y -= 20

    c.setFont("Helvetica", 11)

    address = incident.address or "Not Available"

    c.drawString(50, y, f"Address: {address}")
    y -= 18

    c.drawString(
        50,
        y,
        f"Coordinates: {incident.latitude}, {incident.longitude}"
    )

    y -= 25


    # -------------------------
    # DESCRIPTION
    # -------------------------

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Description")

    y -= 20

    c.setFont("Helvetica", 11)

    description = incident.description or "No description provided."

    text = c.beginText(50, y)
    text.setLeading(15)

    for line in split_text(description, 90):
        text.textLine(line)

    c.drawText(text)

    y = text.getY() - 25


    # -------------------------
    # DETAILED NARRATIVE
    # -------------------------

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Detailed Report")

    y -= 20

    narrative = f"""
On {time_value}, an incident categorized as "{incident.type}" was reported through the
Municipal Incident Reporting System.

The report indicates that the event occurred at {address}. The system recorded
the geographic coordinates of the location as {incident.latitude}, {incident.longitude}.

According to the submitted report description:

"{description}"

The reporting individual also provided photographic evidence through the system
to support the incident report. This information has been logged and made available
for monitoring, verification, and response coordination by the responsible
government authorities.

Further investigation or response actions may be conducted depending on the
nature and severity of the reported incident.
"""

    text = c.beginText(50, y)
    text.setLeading(15)

    for line in split_text(narrative.strip(), 90):
        text.textLine(line)

    c.drawText(text)

    y = text.getY() - 25


    # -------------------------
    # PHOTO EVIDENCE
    # -------------------------

    if incident.photo:

        photo_path = os.path.join(upload_folder, incident.photo)

        if os.path.exists(photo_path):

            c.setFont("Helvetica-Bold", 12)
            c.drawString(50, y, "Photo Evidence")

            y -= 20

            try:

                c.drawImage(
                    photo_path,
                    50,
                    y - 200,
                    width=4 * inch,
                    height=3 * inch,
                    preserveAspectRatio=True
                )

            except:
                pass


    # -------------------------
    # FOOTER
    # -------------------------

    c.setFont("Helvetica", 9)

    c.drawString(
        50,
        40,
        f"Report generated on {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')}"
    )

    c.save()

    return filepath



# -------------------------
# TEXT WRAPPER
# -------------------------

def split_text(text, length):

    words = text.split()
    lines = []
    current = ""

    for word in words:

        if len(current + " " + word) <= length:
            current += " " + word
        else:
            lines.append(current.strip())
            current = word

    if current:
        lines.append(current.strip())

    return lines